### ISSUE TITLE
I am trying to use docker.Client().inspect(IMAGE) but I am seeing Null in new fields for labels.

### ISSUE THREAD

**Issue by rhatdan** [shin-/docker-py#3]
I am working on a Labels patch for docker that allows you to add Labels (Name/Value) pairs into the docker image metadata.  

With the patch installed and the docker inspect is showing the fields but docker-py shows the fields as NULL.  Any idea why?

**Comment by rhatdan** [comment]
Here is the json file from the 

/var/lib/docker/graph/ad7e475cd530ad0c901b5ee5239be21f9892a9a98df0109f28e8711e3a4e3e16
directory

{"id":"ad7e475cd530ad0c901b5ee5239be21f9892a9a98df0109f28e8711e3a4e3e16","parent":"c89451f76613a999e066fadb9df982adc9888323d5cc69daa8571b44fdce2f56","created":"2015-01-16T19:02:15.766416492Z","container":"abce7eb27845d9358c1de5089c1017f7444bf5aed9cc7639088cf6d45a836268","container_config":{"Hostname":"c4e263145f81","Domainname":"","User":"","Memory":0,"MemorySwap":0,"CpuShares":0,"Cpuset":"","AttachStdin":false,"AttachStdout":false,"AttachStderr":false,"PortSpecs":null,"ExposedPorts":null,"Tty":false,"OpenStdin":false,"StdinOnce":false,"Env":["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin","container=docker"],"Cmd":["/bin/sh","-c","#(nop) CMD [/bin/sh -c [“/sbin/init”]]"],"Image":"c89451f76613a999e066fadb9df982adc9888323d5cc69daa8571b44fdce2f56","Volumes":{"[":{},"]":{},"“/sys/fs/cgroup”":{}},"WorkingDir":"","Entrypoint":null,"NetworkDisabled":false,"MacAddress":"","OnBuild":[],"SecurityOpt":null,"Labels":["Vendor=Red Hat","License=GPL","Version=1.0","INSTALL=docker run --privileged -v /dev:/dev -v /sys:/sys -v /run:/run -v /:/host --pid=host --net=host --ipc=host -e LOGDIR=$(LOGDIR) -e CONFDIR=$(CONFDIR) -e DATADIR=$(DATADIR) IMAGE /bin/sh","RUN=docker run foobar walsh"]},"docker_version":"1.4.1-dev","author":"Dan Walsh","config":{"Hostname":"c4e263145f81","Domainname":"","User":"","Memory":0,"MemorySwap":0,"CpuShares":0,"Cpuset":"","AttachStdin":false,"AttachStdout":false,"AttachStderr":false,"PortSpecs":null,"ExposedPorts":null,"Tty":false,"OpenStdin":false,"StdinOnce":false,"Env":["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin","container=docker"],"Cmd":["/bin/sh","-c","[“/sbin/init”]"],"Image":"c89451f76613a999e066fadb9df982adc9888323d5cc69daa8571b44fdce2f56","Volumes":{"[":{},"]":{},"“/sys/fs/cgroup”":{}},"WorkingDir":"","Entrypoint":null,"NetworkDisabled":false,"MacAddress":"","OnBuild":[],"SecurityOpt":null,"Labels":["Vendor=Red Hat","License=GPL","Version=1.0","INSTALL=docker run --privileged -v /dev:/dev -v /sys:/sys -v /run:/run -v /:/host --pid=host --net=host --ipc=host -e LOGDIR=$(LOGDIR) -e CONFDIR=$(CONFDIR) -e DATADIR=$(DATADIR) IMAGE /bin/sh","RUN=docker run foobar walsh"]},"architecture":"amd64","os":"linux","checksum":"tarsum.dev+sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855","Size":0}

**Comment by rhatdan** [comment]
# docker inspect atom
[{
    "Architecture": "amd64",
    "Author": "Dan Walsh",
    "Checksum": "tarsum.dev+sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "Comment": "",
    "Config": {
        "AttachStderr": false,
        "AttachStdin": false,
        "AttachStdout": false,
        "Cmd": [
            "/bin/sh",
            "-c",
            "[“/sbin/init”]"
        ],
        "CpuShares": 0,
        "Cpuset": "",
        "Domainname": "",
        "Entrypoint": null,
        "Env": [
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "container=docker"
        ],
        "ExposedPorts": null,
        "Hostname": "c4e263145f81",
        "Image": "c89451f76613a999e066fadb9df982adc9888323d5cc69daa8571b44fdce2f56",
        "Labels": [
            "Vendor=Red Hat",
            "License=GPL",
            "Version=1.0",
            "INSTALL=docker run --privileged -v /dev:/dev -v /sys:/sys -v /run:/run -v /:/host --pid=host --net=host --ipc=host -e LOGDIR=$(LOGDIR) -e CONFDIR=$(CONFDIR) -e DATADIR=$(DATADIR) IMAGE /bin/sh",
            "RUN=docker run foobar walsh"
        ],
        "MacAddress": "",
        "Memory": 0,
        "MemorySwap": 0,
        "NetworkDisabled": false,
        "OnBuild": [],
        "OpenStdin": false,
        "PortSpecs": null,
        "SecurityOpt": null,
        "StdinOnce": false,
        "Tty": false,
        "User": "",
        "Volumes": {
            "[": {},
            "]": {},
            "“/sys/fs/cgroup”": {}
        },
        "WorkingDir": ""
    },
    "Container": "abce7eb27845d9358c1de5089c1017f7444bf5aed9cc7639088cf6d45a836268",
    "ContainerConfig": {
        "AttachStderr": false,
        "AttachStdin": false,
        "AttachStdout": false,
        "Cmd": [
            "/bin/sh",
            "-c",
            "#(nop) CMD [/bin/sh -c [“/sbin/init”]]"
        ],
        "CpuShares": 0,
        "Cpuset": "",
        "Domainname": "",
        "Entrypoint": null,
        "Env": [
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "container=docker"
        ],
        "ExposedPorts": null,
        "Hostname": "c4e263145f81",
        "Image": "c89451f76613a999e066fadb9df982adc9888323d5cc69daa8571b44fdce2f56",
        "Labels": [
            "Vendor=Red Hat",
            "License=GPL",
            "Version=1.0",
            "INSTALL=docker run --privileged -v /dev:/dev -v /sys:/sys -v /run:/run -v /:/host --pid=host --net=host --ipc=host -e LOGDIR=$(LOGDIR) -e CONFDIR=$(CONFDIR) -e DATADIR=$(DATADIR) IMAGE /bin/sh",
            "RUN=docker run foobar walsh"
        ],
        "MacAddress": "",
        "Memory": 0,
        "MemorySwap": 0,
        "NetworkDisabled": false,
        "OnBuild": [],
        "OpenStdin": false,
        "PortSpecs": null,
        "SecurityOpt": null,
        "StdinOnce": false,
        "Tty": false,
        "User": "",
        "Volumes": {
            "[": {},
            "]": {},
            "“/sys/fs/cgroup”": {}
        },
        "WorkingDir": ""
    },
    "Created": "2015-01-16T19:02:15.766416492Z",
    "DockerVersion": "1.4.1-dev",
    "Id": "ad7e475cd530ad0c901b5ee5239be21f9892a9a98df0109f28e8711e3a4e3e16",
    "Os": "linux",
    "Parent": "c89451f76613a999e066fadb9df982adc9888323d5cc69daa8571b44fdce2f56",
    "Size": 0,
    "VirtualSize": 492348843
}
]

**Comment by rhatdan** [comment]
# python -c 'import docker; print(docker.Client().inspect_image("atom"))'
{u'Comment': u'', u'Container': u'abce7eb27845d9358c1de5089c1017f7444bf5aed9cc7639088cf6d45a836268', u'DockerVersion': u'1.4.1-dev', u'Os': u'linux', u'Author': u'Dan Walsh', u'Checksum': u'tarsum.dev+sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855', u'Created': u'2015-01-16T19:02:15.766416492Z', u'VirtualSize': 492348843, u'Architecture': u'amd64', u'ContainerConfig': {u'Env': [u'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin', u'container=docker'], u'Hostname': u'c4e263145f81', u'Entrypoint': None, u'PortSpecs': None, u'Memory': 0, u'OnBuild': [], u'OpenStdin': False, u'MacAddress': u'', u'Cpuset': u'', u'User': u'', u'CpuShares': 0, u'AttachStdout': False, u'NetworkDisabled': False, u'WorkingDir': u'', u'Cmd': [u'/bin/sh', u'-c', u'#(nop) CMD [/bin/sh -c [\u201c/sbin/init\u201d]]'], u'StdinOnce': False, u'AttachStdin': False, u'MemorySwap': 0, u'Volumes': {u'\u201c/sys/fs/cgroup\u201d': {}, u'[': {}, u']': {}}, u'Tty': False, u'AttachStderr': False, u'Domainname': u'', u'Image': u'c89451f76613a999e066fadb9df982adc9888323d5cc69daa8571b44fdce2f56', u'Labels': [u'Vendor=Red Hat', u'License=GPL', u'Version=1.0', u'INSTALL=docker run --privileged -v /dev:/dev -v /sys:/sys -v /run:/run -v /:/host --pid=host --net=host --ipc=host -e LOGDIR=$(LOGDIR) -e CONFDIR=$(CONFDIR) -e DATADIR=$(DATADIR) IMAGE /bin/sh', u'RUN=docker run foobar walsh'], u'SecurityOpt': None, u'ExposedPorts': None}, u'Parent': u'c89451f76613a999e066fadb9df982adc9888323d5cc69daa8571b44fdce2f56', u'Config': {u'Env': [u'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin', u'container=docker'], u'Hostname': u'c4e263145f81', u'Entrypoint': None, u'PortSpecs': None, u'Memory': 0, u'OnBuild': [], u'OpenStdin': False, u'MacAddress': u'', u'Cpuset': u'', u'User': u'', u'CpuShares': 0, u'AttachStdout': False, u'NetworkDisabled': False, u'WorkingDir': u'', u'Cmd': [u'/bin/sh', u'-c', u'[\u201c/sbin/init\u201d]'], u'StdinOnce': False, u'AttachStdin': False, u'MemorySwap': 0, u'Volumes': {u'\u201c/sys/fs/cgroup\u201d': {}, u'[': {}, u']': {}}, u'Tty': False, u'AttachStderr': False, u'Domainname': u'', u'Image': u'c89451f76613a999e066fadb9df982adc9888323d5cc69daa8571b44fdce2f56', u'Labels': [u'Vendor=Red Hat', u'License=GPL', u'Version=1.0', u'INSTALL=docker run --privileged -v /dev:/dev -v /sys:/sys -v /run:/run -v /:/host --pid=host --net=host --ipc=host -e LOGDIR=$(LOGDIR) -e CONFDIR=$(CONFDIR) -e DATADIR=$(DATADIR) IMAGE /bin/sh', u'RUN=docker run foobar walsh'], u'SecurityOpt': None, u'ExposedPorts': None}, u'Id': u'ad7e475cd530ad0c901b5ee5239be21f9892a9a98df0109f28e8711e3a4e3e16', u'Size': 0}

**Comment by rhatdan** [comment]
Never mind now it seems to be working.

**Comment by shin-** [comment]
Let us know if you're still having issues, Also for future reference, you can have nicer code formatting in Github issues by surrounding code blocks by triple backquotes: <code>```</code>

**Comment by shin-** [comment]
Oh and the official repository has moved here: https://github.com/docker/docker-py
